# Generated by Django 5.1.6 on 2025-02-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
