# Generated by Django 5.1.6 on 2025-02-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='phone_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
