# Generated by Django 5.1.6 on 2025-02-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_transactionflutter_transactionpaystack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionpaystack',
            name='access_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactionpaystack',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
